name: no-more-idle
version: '1.0.0'
summary: Prevents the system from going idle by simulating user activity.
description: |
  A powerful Python script designed to prevent your computer from going idle. This script simulates user activity by moving the mouse, scrolling, or pressing keys at set intervals. It is ideal for keeping your system active during extended periods of inactivity.
base: core20
confinement: strict
grade: stable

apps:
  no-more-idle:
    command: bin/no-more-idle
    plugs: 
      - network
      - network-bind
      - x11
      - wayland

parts:
  no-more-idle:
    plugin: python
    source: .
    stage-packages:
      - python3
      - python3-pip
    python-packages:
      - pynput
